dist: trusty
language: node_js
sudo: true

env:
  - CXX=g++-4.8

node_js:
  - 4
  - 6
  - 7

notifications:
  email:
    - lilleman@larvit.se
    - tobias@nublar.se

before_install:
  - $CXX --version
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch start

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

services:
  - rabbitmq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-set-default

before_script:
  - sleep 15

script: ESCONFFILE=es_travis.json INTCONFFILE=amqp_travis.json npm test
