dist: trusty
language: node_js
sudo: true

env:
  - CXX=g++-4.8

node_js:
  - 6
  - 7
  - 8
  - 9

notifications:
  email:
    - lilleman@larvit.se
    - tobias@nublar.se

before_install:
  - $CXX --version
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch start

before_script:
  - mysql -e 'CREATE DATABASE test'
  - sleep 15

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

services:
  - mysql

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-set-default

script: DBCONFFILE=db_travis.json ESCONFFILE=es_travis.json npm test
